exports.NOVEL_ACTION = 'ACTION';
exports.NOVEL_COMEDY = 'COMEDY';
exports.NOVEL_DRAMA = 'DRAMA';
exports.NOVEL_FANTASY = 'FANTASY';
exports.NOVEL_ROMANCE = 'ROMANCE';
exports.NOVEL_THILLER = 'THILLER';

exports.NOVEL_STATUS_ONGOING = 'ONGOING';
exports.NOVEL_STATUS_COMPLETED = 'COMPLETED';

exports.CHAPTER_PUBLISH = 'PUBLISH';
exports.CHAPTER_UNPUBLISH = 'UNPUBLISH';
