exports.NOVEL_ACTION = 'ACTION';
exports.NOVEL_COMEDY = 'COMEDY';
exports.NOVEL_DRAMA = 'DRAMA';
exports.NOVEL_FANTASY = 'FANTASY';
exports.NOVEL_ROMANCE = 'ROMANCE';
exports.NOVEL_THRILLER = 'THRILLER';

exports.NOVEL_STATUS_ONGOING = 'ONGOING';
exports.NOVEL_STATUS_COMPLETED = 'COMPLETED';

exports.CHAPTER_PUBLISH = 'PUBLISH';
exports.CHAPTER_UNPUBLISH = 'UNPUBLISH';

exports.QUERY_NOVEL_FIND_ALL = 'ALL';
exports.QUERY_NOVEL_FIND_ACTION = 'ACTION';
exports.QUERY_NOVEL_FIND_COMEDY = 'COMEDY';
exports.QUERY_NOVEL_FIND_DRAMA = 'DRAMA';
exports.QUERY_NOVEL_FIND_FANTASY = 'FANTASY';
exports.QUERY_NOVEL_FIND_ROMANCE = 'ROMANCE';
exports.QUERY_NOVEL_FIND_THRILLER = 'THRILLER';
